### ISSUE TITLE
dev-repo errors

### ISSUE THREAD

**Issue by mmottl** [OCamlPro/opam-builder#1]
The report page flags many packages as having broken `dev-repo` fields:

```
42: The 'dev-repo' field doesn't use version control. You may use URLs of the form "git+https://" or a ".hg" or ".git" suffix
```

I couldn't find any documentation on the correct syntax for that field.  Most packages seem to use a format like e.g.:

```
dev-repo: "https://github.com/mmottl/aifad.git"
```

The above seemed fine to me.  Could you please advise on the correct syntax for this field or relax the syntax restrictions to support this syntax?

**Comment by lefessan** [comment]
To the best of my knowledge, there is no good solution to the dev-repo warnings. Using "git+https" only works with current versions of OPAM, but triggers an error with older versions. I think I will just filter these warnings out.

**Comment by lefessan** [comment]
Commit #ace4d6d6c85624d61b874b9414aa0a0ad31fdf85 removes printing of warnings 37 and 42
