### ISSUE TITLE
Download failures of ppx_test.1.3.1, pcre.7.2.3, etc.

### ISSUE THREAD

**Issue by camlspotter** [OCamlPro/opam-builder#10]
Thanks for providing opam-builder, it is nice to check my package installablitiy.

BTW, ppx_test.1.3.1 and pcre.7.2.3 always fail to install since their source archive download fail.  For example, see http://opam.ocamlpro.com/builder/html/orakuda/orakuda.2.0.0/f998aeb546721157c67b2322d8ca5c3a

This affects all the dependent packages over these: they are all orange.

I do not see the reason why these downloads fail. Locally I could wget these source archives w/o problem.

**Comment by lefessan** [comment]
These packages are now green, so I suppose the problem has disappeared. I don't really now why downloads may fail, indeed, we should add a way to restart builds that failed for a download failure, after a given time.
